In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.style

In [3]:
import matplotlib.pyplot as plt

In [4]:
import xlrd

In [8]:
df = pd.ExcelFile(r'C:\Users\rcmlp.12\Desktop\working file\python path\Mirep_data_02_jun_22.xlsx')

In [9]:
df.sheet_names

['05',
 '10',
 '11',
 '12',
 '15',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '3',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '38',
 '45',
 '46',
 '47',
 '49',
 '5',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '6',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '9',
 'Sheet2',
 'Sheet1']

In [12]:
df2=df.parse('9')
df2

        CHAPTER             9     Unnamed: 2
0    MONTH_CODE         (All)            NaN
1           NaN           NaN            NaN
2    Row Labels  Sum of MIREP  Sum of CYCLES
3        N249BA             0             21
4        N263SG             0              5
5        N322SG             0              3
6        N404KZ             0            151
7        N405KZ             0            152
8        N406KZ             0            169
9        N407KZ             0             67
10       N408MC             0            159
11       N409MC             0            193
12       N412MC             0            188
13       N415MC             0            124
14       N416MC             0            167
15       N418MC             0            192
16       N419MC             0            178
17       N429MC             0            158
18       N445MC             0            175
19       N446MC             0            197
20       N450PA             0            155
21       N451PA             0            187
22       N452PA             0            112
23       N453PA             0            189
24       N454PA             0            182
25       N471MC             0            150
26       N472MC             0            167
27       N473MC             0             88
28       N475MC             0            204
29       N476MC             0            215
30       N477MC             0             95
31       N480MC             0             17
32       N481MC             0             50
33       N482MC             0             58
34       N485MC             0            125
35       N486MC             0            167
36       N487MC             0            181
37       N489MC             0            168
38       N492MC             0            144
39       N493MC             1            177
40       N496MC             0            116
41       N498MC             0            194
42       N499MC             0            167
43       N508KZ             0            123
44       N718BA             0             12
45       N747BC             0             22
46       N850GT             1            143
47       N851GT             0            133
48       N852GT             0            147
49       N853GT             0            140
50       N854GT             0            187
51       N855GT             0            168
52       N856GT             0            160
53       N857GT             0            171
54       N858GT             0            182
55       N859GT             0            182
56  Grand Total             2           7377